services:
  - type: web
    name: whisppr-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SMS_PROVIDER
        value: whatsapp
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ID
        sync: false
      - key: WHISPPR_API_KEY
        sync: false
      - key: MAP_BASE_URL
        sync: false
